### ISSUE TITLE
Help from Rahul Bhalley

### ISSUE THREAD

**Issue by philipturner** [philipturner/metal-xla#1]
Continuing https://github.com/apple/coremltools/issues/1374#issuecomment-1000253157

@RahulBhalley one idea I thought of quickly is that you can help @BradLarson and the rest of the old S4TF team with fixing autodiff bugs. This is tedious and requires investing quite a bit of time in understanding the compiler beforehand, so it's okay if you decide not to do this because you don't want to. This task is related to IR compilers and I thought of it when you said you were interested in learning about intermediate languages.

**Comment by RahulBhalley** [comment]
> This task is related to IR compilers and I thought of it when you said you were interested in learning about intermediate languages.

Thanks for the idea 💡. I believe I find more interest in understanding MSL. Understanding it and building kernels here for S4TF will help me personally also in writing my own kernels in future for my own app projects. 

I'd like you to please guide me regarding that. Is [Programming Metal in iOS](https://www.youtube.com/playlist?list=PL23Revp-82LJG3vcDPm8w7b5HTKjBOY0W) a good start?

**Comment by philipturner** [comment]
Learning MSL is the least of your worries and actually a terrible way to use your time right now. Making simple kernels is super easy and I can do that in my sleep. The real skill you need for that task is hundreds of hours debugging GPGPU workflows.

Look at MetalFFT. It’s entirely a wrapper around a few shaders, but 92% of the code is Swift and >60% of my time was spent on stuff besides the shaders.

I like your interest in MSL, but for your knowledge on that to be useful, you would have to dedicate much more time than one hour a day for 4 months. You can find out how reluctant I was to devote such time in my article about the [first affordable AR headset](https://philipturner.github.io/first-affordable-ar-headset).

**Comment by philipturner** [comment]
I was thinking that you could help out with the higher-level aspect of GPU acceleration. Work on a draft for the MetalXLA compiler that maps from S4TF’s ops to MPS Graph or MPS, while leaving the unsupported ones to CPU. For example, I don’t have the time to tabulate each individual S4TF raw op and exactly all the ones missing from MPS and MPS Graph.

**Comment by philipturner** [comment]
If you choose to draft MetalXLA instead of helping out with MetalSLC, that would work as well. You have some experience with MPS and MPS Graph, which is good to begin with. What I need in a draft is a general way to segment an arbitrary stream of ops (such as XLA) into what is and isn't compatible with:
- MPS
- MPSNNGraph
- MPSGraph
- MLCGraph
- Trivial, O(n) custom shaders - Mish activation function is an example; I could give you private access to my unpublished experiments on custom shaders for DL4S

Then, execute that stream of ops. Instead of worrying about performance, just worry about getting it to work without bugs. That would be a major direct help, giving me a base to refer to when I finish side-loading Swift on Colab.

You could also switch between the two tasks periodically, so that you don't get burnt out on either one. In that case, I recommend that you start out with MetalSLC because it gives you more knowledge and background about GPU. That knowledge is generally useful for any GPU task, which would be more productive for tackling MPS Graph.

**Comment by philipturner** [comment]
I prefer that you try option 2, but the others are there as alternatives.

**Comment by philipturner** [comment]
Change of plans:

@RahulBhalley, I’m delegating the initial research stage of MetalXLA to you, similar to what I did with DL4S-Experiments. I’ll make the DL4S experiments entirely open-source so you can have full access to the test suite I made for them.

By February 2022, I need a product that compiles a tiny set of ops into two groups: compatible and incompatible with MPS Graph. Process a random stream of ops, partitioning sub-streams into MPSGraphs and compiling when a stream is 2 ops or more. Execute the rest in any manner, as long as it produces valid, bug-free output. Completely ignore performance for the time being.

Do this research in a personal repository owned by your account, which gives you the most flexibility. Please produce a robust test suite for your research, accounting for all edge cases and even instances where a tensor’s dimensions exceed the maximum size of a Metal texture. The merging of your research into MetalXLA will not be done through a PR.

Delegating this task to you will buy me some time while I do a lot of correspondence with the S4TF team about the publicity of S4TF’s resurrection. When I get back, we can work together to race to finish a beta Metal backend before PyTorch does.

@compnerd pinging you.

**Comment by RahulBhalley** [comment]
Following this https://github.com/vojtamolda/Sundials.swift/issues/2#issuecomment-1002396931, I believe this is a highly risky task with almost certainly no valuable outcomes. Hence, I cannot devote my time and efforts in this work. 

All the best!

**Comment by philipturner** [comment]
@RahulBhalley what are you planning to explore instead? Just curious.

**Comment by RahulBhalley** [comment]
> The way to just portrayed my effort to resurrect something so loved in the open-source community made me feel bitter. You didn’t react this way to @palle-k’s effort with DL4S. I’ll set aside my feelings for now.

@philipturner I heartily apologize, I didn't mean any of my comments to sound rude.

> Although it is risky, I objectively believe that this can be done. I am a high schooler, but this is not a rash decision. Your contribution would have reduced that risk and been a major help.

But I'm not a pro at Metal programming. I just started studying `MPSGraph` this year whereas we need `MPS` instead which has similar API calls to vanilla Metal. Also you're waaay more experienced and smart at this than me. I'm sure I'll learn a lot along the way but this work requires a lot of effort and long-term commitment. I do share goal with you of making Swift become recognized well in deep learning community. But I would wanna do something new instead of continue building what's left untouched for almost a year. For instance, NumPy wasn't made forward- and backward-AD compatible but instead JAX was created. Making new feels fresher than continuing what's been stopped working on. 

> @RahulBhalley what are you planning to explore instead? Just curious.

Still working on my app and focus on Metal (again, for my app) in my spare time.
