### ISSUE TITLE
Move conversation to Discord

### ISSUE THREAD

**Issue by RahulBhalley** [philipturner/metal-xla#3]
Hey @philipturner, 

I think we should move our conversation to a Discord server because conversation is better suited for a messaging platform. I know GitHub's Discussion feature exists but it's still not competitive with Discord in term of conversation. 

And, of course, raising issues and conversing about it here when making a PR is best done on GitHub. But just conversing on higher level decision making is weird in issues. In Discord, we can have channels for conversation on different topics. 

Anyone who is interested in further development of S4TF may join the **Swift for TensorFlow** server via this [invitation link](https://discord.gg/evDrqfPR).

**Comment by philipturner** [comment]
I don’t think that’s more appropriate. What’s wrong with our conversation being open for the public to see?

**Comment by RahulBhalley** [comment]
Okay. Discord is just a suggestion and can be drop.
